// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3dEg7xfAjmgsBb2hvi1i5P
// Component: ylFN5775Wbu
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Modal from "../../Modal"; // plasmic-import: cteLUFm9gHi/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_signup_modal.module.css"; // plasmic-import: 3dEg7xfAjmgsBb2hvi1i5P/projectcss
import sty from "./PlasmicExamplePage.module.css"; // plasmic-import: ylFN5775Wbu/css

export type PlasmicExamplePage__VariantMembers = {};

export type PlasmicExamplePage__VariantsArgs = {};
type VariantPropType = keyof PlasmicExamplePage__VariantsArgs;
export const PlasmicExamplePage__VariantProps = new Array<VariantPropType>();

export type PlasmicExamplePage__ArgsType = {};
type ArgPropType = keyof PlasmicExamplePage__ArgsType;
export const PlasmicExamplePage__ArgProps = new Array<ArgPropType>();

export type PlasmicExamplePage__OverridesType = {
  root?: p.Flex<"div">;
  modal?: p.Flex<typeof Modal>;
};

export interface DefaultExamplePageProps {}

function PlasmicExamplePage__RenderFunc(props: {
  variants: PlasmicExamplePage__VariantsArgs;
  args: PlasmicExamplePage__ArgsType;
  overrides: PlasmicExamplePage__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <Modal
            data-plasmic-name={"modal"}
            data-plasmic-override={overrides.modal}
            className={classNames("__wab_instance", sty.modal)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "modal"],
  modal: ["modal"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  modal: typeof Modal;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicExamplePage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicExamplePage__VariantsArgs;
    args?: PlasmicExamplePage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicExamplePage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicExamplePage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicExamplePage__ArgProps,
      internalVariantPropNames: PlasmicExamplePage__VariantProps
    });

    return PlasmicExamplePage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicExamplePage";
  } else {
    func.displayName = `PlasmicExamplePage.${nodeName}`;
  }
  return func;
}

export const PlasmicExamplePage = Object.assign(
  // Top-level PlasmicExamplePage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    modal: makeNodeComponent("modal"),

    // Metadata about props expected for PlasmicExamplePage
    internalVariantProps: PlasmicExamplePage__VariantProps,
    internalArgProps: PlasmicExamplePage__ArgProps
  }
);

export default PlasmicExamplePage;
/* prettier-ignore-end */
